pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "kavin4066/todo-dotnet:latest"
        DOCKER_USER = credentials('docker-username')
        DOCKER_PASS = credentials('docker-password')
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/kavinraj710/ToDo.git'
            }
        }

        stage('Build .NET') {
            steps {
                sh '''
                dotnet restore
                dotnet build --configuration Release
                '''
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                sh '''
                dotnet tool install --global dotnet-sonarscanner

                export PATH="$PATH:/var/jenkins_home/.dotnet/tools"

                dotnet sonarscanner begin \
                  /k:"kavinraj710_ToDo" \
                  /o:"kavinraj710" \
                  /d:sonar.login=$SONAR_TOKEN

                dotnet build

                dotnet sonarscanner end \
                  /d:sonar.login=$SONAR_TOKEN
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push $DOCKER_IMAGE
                '''
            }
        }

        stage('Deploy via CodeDeploy') {
            steps {
                sh '''
                aws deploy create-deployment \
                --application-name todo-dotnet \
                --deployment-group-name todo-group \
                --deployment-config-name CodeDeployDefault.AllAtOnce \
                --github-location repository=kavinraj710/ToDo,commitId=main
                '''
            }
        }
    }
}
